<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array (
		'key' => 'group_5734ed4f7bf71',
		'title' => 'Store Settings',
		'fields' => array (
			array (
				'key' => 'field_573b8682686c6',
				'label' => 'Duration System',
				'name' => 'ldadstore_duration_system',
				'type' => 'select',
				'instructions' => '<p>Pick a system to sell ad space with. These are the time blocks customers may purchase ad slots with.</p>

<p><strong>Avoid changing this frequently.</strong> Existing ads will not change their start/end dates so you may have gaps in your advertisements if you change the dates.</p>',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'Monthly' => 'Monthly',
					'Custom' => 'Custom',
				),
				'default_value' => array (
					0 => 'Monthly',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'disabled' => 0,
				'readonly' => 0,
			),
			array (
				'key' => 'field_573caf6158151',
				'label' => 'Months in advance',
				'name' => 'ldadstore_months_in_advance',
				'type' => 'number',
				'instructions' => 'How many months can ads be purchased in advance?',
				'required' => 1,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_573b8682686c6',
							'operator' => '==',
							'value' => 'Monthly',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 12,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => '',
				'step' => 1,
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_573b4964612f5',
				'label' => 'Time Slots',
				'name' => 'ldadstore_time_slots',
				'type' => 'repeater',
				'instructions' => '<p>These time slots can be purchased by advertisers. Each slot starts on the given date, and ends at the beginning of the next date.</p>

<p><strong>The last time slot will not be purchasable</strong> as the end date cannot be determined.</p>',
				'required' => 1,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_573b8682686c6',
							'operator' => '==',
							'value' => 'Custom',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 1,
				'max' => '',
				'layout' => 'table',
				'button_label' => 'Add Time Slot',
				'sub_fields' => array (
					array (
						'key' => 'field_573b5378bc968',
						'label' => 'Name',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_573b5393bc969',
						'label' => 'Start Date',
						'name' => 'start_date',
						'type' => 'date_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'display_format' => 'F j, Y',
						'return_format' => 'Ymd',
						'first_day' => 0,
					),
				),
			),
			array (
				'key' => 'field_5774004160742',
				'label' => 'Custom Tabs',
				'name' => 'ld_ad_store_custom_pages',
				'type' => 'repeater',
				'instructions' => 'You can add custom pages to the menu bar on navigation pages here.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_5774009060743',
				'min' => 1,
				'max' => 1,
				'layout' => 'table',
				'button_label' => 'Add Item',
				'sub_fields' => array (
					array (
						'key' => 'field_5774009060743',
						'label' => 'Page',
						'name' => 'page',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => array (
						),
						'taxonomy' => array (
						),
						'allow_null' => 0,
						'multiple' => 0,
						'return_format' => 'id',
						'ui' => 1,
					),
					array (
						'key' => 'field_5774012560744',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
				),
			),
			array (
				'key' => 'field_579156967a309',
				'label' => 'Custom button for non-logged-in users',
				'name' => 'ld_ad_store_custom_button',
				'type' => 'repeater',
				'instructions' => 'You can add a custom button to the options shown to non-logged-in users here',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_5774009060743',
				'min' => 1,
				'max' => 1,
				'layout' => 'table',
				'button_label' => 'Add Item',
				'sub_fields' => array (
					array (
						'key' => 'field_579156967a30a',
						'label' => 'Page',
						'name' => 'page',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => array (
						),
						'taxonomy' => array (
						),
						'allow_null' => 0,
						'multiple' => 0,
						'return_format' => 'id',
						'ui' => 1,
					),
					array (
						'key' => 'field_579156967a30b',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
				),
			),
			array (
				'key' => 'field_57757800285aa',
				'label' => 'Admin Review Email',
				'name' => 'ld_ad_store_review_email',
				'type' => 'email',
				'instructions' => 'Email address to send admin approval notifications. If empty, the default administrator will receive the notification.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'ld-ad-store',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

endif;